apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: litellm-secrets
data:
  OPENAI_API_KEY: {{ .Values.global.openaiApiKey | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.global.anthropicApiKey | b64enc }}
  DEEPSEEK_API_KEY: {{ .Values.global.deepseekApiKey | b64enc }}
  GOOGLE_API_KEY: {{ .Values.global.googleApiKey | b64enc }}
