apiVersion: v1
kind: Service
metadata:
  name: {{ include "crs.litellm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "litellm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "litellm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: litellm 