apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sentinel.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: sentinel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sentinel.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: sentinel
        b3yond.org/anti-affinity-group: utilities
    spec:
      tolerations:
        - key: "b3yond.org/role"
          operator: "Equal"
          value: "user"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: b3yond.org/role
                operator: In
                values:
                - user
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: b3yond.org/anti-affinity-group
                    operator: In
                    values:
                      - isolated
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: b3yond.org/anti-affinity-group
                      operator: In
                      values:
                        - utilities
                topologyKey: kubernetes.io/hostname
      containers:
        - name: sentinel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
          env:
            - name: RABBITMQ_HOST
              value: '{{ include "crs.rabbitmq.fullname" . }}'
            - name: RABBITMQ_USER
              value: '{{ .Values.global.rabbitmq.auth.username }}'
            - name: RABBITMQ_PASSWORD
              value: '{{ .Values.global.rabbitmq.auth.password }}'
            - name: DATABASE_URL
              value: {{ .Values.global.database.connectionString }}
            - name: QUEUE_NAME
              value: "prime_fuzzing_queue"
            - name: OSS_FUZZ_PATH
              value: "./fuzz-tooling"
            - name: REDIS_HOST
              value: '{{ include "crs.redis-master.fullname" . }}'
            - name: REDIS_SENTINEL_HOSTS
              value: '{{ include "crs.redis-headless.fullname" . }}:26379'
            - name: REDIS_MASTER
              value: "mymaster"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: '{{ include "crs.otel-collector.endpoint.http" . }}'
          volumeMounts:
            - name: crs-fileshare
              mountPath: /crs
      volumes:
        - name: crs-fileshare
          persistentVolumeClaim:
            claimName: {{ .Values.global.pvc.name }}
      imagePullSecrets:
        - name: {{ .Values.secret }}
      initContainers:
        - name: wait-for-scheduler
          image: curlimages/curl:8.12.1
          command: ["sh", "-c", "until [ \"$(curl -s -o /dev/null -w '%{http_code}' http://{{ .Values.global.serviceName.scheduler }}:8080/health)\" -eq 200 ]; do echo waiting for scheduler; sleep 2; done"]
          resources:
            requests:
              cpu: 500m