[package]
name = "callgraph_rt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
once_cell = "1.10"
ctor = "0.1"
libc = "0.2"
backtrace = { version = "0.3", features = ["cpp_demangle"] }
lazy_static = "1.5.0"
dashmap = "6.1.0"
