apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.serviceName.mock }}
  labels:
    app.kubernetes.io/name: {{ include "mock.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mock.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
