$schema: ./schema/mcp-agent.config.schema.json

logger:
  transports: [console, file]
  level: info
  # progress_display: true
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp" # Options: "timestamp" or "session_id"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    # slack:
    #   command: "npx"
    #   args: ["-y", "@modelcontextprotocol/server-slack"]
      # consider defining sensitive values in a separate mcp_agent.secrets.yaml file
      # env:
      #   SLACK_BOT_TOKEN: "xoxb-your-bot-token"
      #   SLACK_TEAM_ID": "T01234567"
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch", "--ignore-robots-txt"]
    filesystem:
      command: "npx"
      args:
        [
          "-y",
          "@modelcontextprotocol/server-filesystem"
        ]
    treesitter:
      command: "/usr/bin/python3"
      args:
        [
          "-m",
          "mcp_server_tree_sitter.server"
        ]

openai:
  default_model: gpt-4.1-2025-04-14

anthropic:
  # default_model: claude-3-7-sonnet-20250219
  default_model: claude-3-5-sonnet-20241022

google:
  default_model: gemini-2.5-pro-preview-03-25
