apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "javaslice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "javaslice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "javaslice.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: javaslice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "javaslice.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: javaslice
        b3yond.org/anti-affinity-group: isolated
    spec:
      tolerations:
        - key: "b3yond.org/role"
          operator: "Equal"
          value: "user"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: b3yond.org/role
                operator: In
                values:
                - user
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: b3yond.org/anti-affinity-group
                    operator: In
                    values:
                      - isolated
                      - utilities
              topologyKey: kubernetes.io/hostname
      containers:
        - name: javaslice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            requests:
              cpu: {{ min .Values.global.resources.requests.cpu 4 }}
            limits:
              cpu: {{ max .Values.global.resources.limits.cpu 8 }}
          env:
            - name: POLL_INTERVAL_SECONDS
              value: "60"
            - name: CRS_MOUNT_PATH
              value: "/crs"
            - name: REDIS_HOST
              value: '{{ include "crs.redis-master.fullname" . }}'
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SENTINEL_HOSTS
              value: '{{ include "crs.redis-headless.fullname" . }}:26379'
            - name: REDIS_MASTER
              value: "mymaster"
            - name: WORK_DIR
              value: "/tmp/javaslice"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: '{{ .Values.global.otel.endpoint }}'
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: '{{ .Values.global.otel.headers }}'
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: '{{ .Values.global.otel.protocol }}'
          volumeMounts:
            - name: crs-fileshare
              mountPath: /crs
      volumes:
        - name: crs-fileshare
          persistentVolumeClaim:
            claimName: {{ .Values.global.pvc.name }}
      imagePullSecrets:
        - name: {{ .Values.secret }}
      initContainers:
        - name: wait-for-scheduler
          image: curlimages/curl:8.12.1
          command: ["sh", "-c", "until [ \"$(curl -s -o /dev/null -w '%{http_code}' http://{{ .Values.global.serviceName.scheduler }}:8080/health)\" -eq 200 ]; do echo waiting for scheduler; sleep 2; done"]
          resources:
            requests:
              cpu: 500m
