image:
  repository: ghcr.io/aixcc-finals/afc-crs-42-b3yond-6ug/b3compile
  tag: "gold"
secret: ghcr-registry
replicaCount: 0
scale:
  queue: artifact_queue
  targetValue: 1
  minReplicaCount: 0
  maxReplicaCount: 8
  cooldownPeriod:  3600
